version: '3.8.10'

services:
  web:
    build: .
    command: gunicorn Social_Networking.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-secret-key
    depends_on: []
